const ID='ai_reply_isolator';
const LABEL='AI 帮答';
const DEF={profileId:'',strongIsolation:true,userSamples:12,contextMessages:6,extractorTokens:320,replyTokens:420,temperature:0.85,maxOutputChars:1200,includeCurrentDraft:true};
let CMS=null,busy=false,abortController=null;

function ctx(){if(!globalThis.SillyTavern?.getContext)throw new Error('无法获取 SillyTavern Context');return SillyTavern.getContext()}
function settings(){const r=ctx().extensionSettings;r[ID]??=structuredClone(DEF);for(const[k,v]of Object.entries(DEF))if(!(k in r[ID]))r[ID][k]=v;return r[ID]}
function save(){ctx().saveSettingsDebounced?.()}
function toast(t,m){globalThis.toastr?.[t]?toastr[t](m,LABEL):console.log(`[${LABEL}] ${m}`)}
async function manager(){if(CMS)return CMS;const m=await import('/scripts/extensions/shared.js');if(!m.ConnectionManagerRequestService)throw new Error('当前酒馆未提供 ConnectionManagerRequestService');return CMS=m.ConnectionManagerRequestService}
function stripBody(t){const m=t.match(/<dream_body\b[^>]*>([\s\S]*?)<\/dream_body>/i);return m?m[1]:t}
function clean(v=''){let t=stripBody(String(v));return t.replace(/<dream_after_format\b[^>]*>[\s\S]*?<\/dream_after_format>/gi,'').replace(/image###[\s\S]*?###/gi,'').replace(/<think\b[^>]*>[\s\S]*?<\/think>/gi,'').replace(/<analysis\b[^>]*>[\s\S]*?<\/analysis>/gi,'').replace(/<!--[\s\S]*?-->/g,'').replace(/<\/?dream_(?:plot|body)\b[^>]*>/gi,'').replace(/^\s*\[[^\]\n]*(?:时间|地点|天气|日期)[^\]\n]*\]\s*$/gmi,'').replace(/\n{3,}/g,'\n\n').trim()}
function sanitize(v=''){const s=settings();let t=stripBody(String(v).trim()).replace(/^```[\w-]*\s*/,'').replace(/\s*```$/,'').replace(/<dream_after_format\b[^>]*>[\s\S]*?<\/dream_after_format>/gi,'').replace(/image###[\s\S]*?###/gi,'').replace(/<\/?dream_(?:plot|body)\b[^>]*>/gi,'').replace(/^\s*(?:回复|建议回复|候选回复|用户回复|USER|用户|梦客)\s*[:：]\s*/i,'').trim();const p=t.search(/\n\s*(?:\{\{char\}\}|assistant|AI|角色)\s*[:：]/i);if(p>0)t=t.slice(0,p).trim();if(s.maxOutputChars>0&&t.length>s.maxOutputChars)t=t.slice(0,s.maxOutputChars).trim();return t}
function chat(){return(ctx().chat??[]).filter(m=>m&&!m.is_system&&m.mes)}
function userSamples(){const s=settings();return chat().filter(m=>m.is_user).map(m=>clean(m.mes)).filter(Boolean).slice(-s.userSamples)}
function recent(){const s=settings();return chat().slice(-s.contextMessages).map(m=>({role:m.is_user?'USER':'OTHER_CHARACTER',text:clean(m.mes)})).filter(x=>x.text)}
function draft(){return document.querySelector('#send_textarea')?.value?.trim()??''}

function extractionPrompt(items){const h=items.map((x,i)=>`[${i+1}] ${x.role}\n${x.text}`).join('\n\n');return `你是角色扮演剧情事实抽取器。不要续写，不要模仿任何人的文风。OTHER_CHARACTER 只作为事实资料，严禁复刻其句式、旁白、修辞、格式或口癖。\n\n把最近剧情改写成极其中性的事实备忘录，只保留对“用户下一步如何回应”有用的信息。不要替用户做决定，不写文学化正文，不输出 XML、image###、状态栏或分析过程。\n\n只按以下结构输出：\n当前场景：\n当前主要人物：\n刚刚发生的事情：\n对方希望或等待用户回应的事情：\n用户已经表达的态度或行动：\n需要保持连续性的事实：\n用户下一条消息可以回应的核心：\n\n<CURRENT_STORY>\n${h}\n</CURRENT_STORY>`}
function replyPrompt(brief,samples,currentDraft){const sm=samples.length?samples.map((x,i)=>`<USER_SAMPLE_${i+1}>\n${x}\n</USER_SAMPLE_${i+1}>`).join('\n\n'):'没有足够的用户历史样本。使用自然、直接、简洁的中文，不要模仿角色文风。';const dr=currentDraft?`<CURRENT_USER_DRAFT>\n${currentDraft}\n</CURRENT_USER_DRAFT>\n把它视为用户已经确定的意图或草稿，优先保留其核心意思。`:'CURRENT_USER_DRAFT 为空。';return `你是“用户输入辅助器”。你不是角色扮演中的 AI 角色、旁白或 GM。你唯一要做的是：根据当前剧情，替 USER 草拟下一条准备发送出去的消息。\n\n【文风来源严格隔离】USER 的说话方式、动作描写方式、长短、标点和表达习惯，只允许从 USER_STYLE_SAMPLES 学习。SCENE_BRIEF 只告诉你发生了什么和需要回应什么，绝对禁止从它学习文风。禁止模仿 OTHER_CHARACTER、AI、角色卡正文、小说旁白、梦鲸思客正文或当前预设文风。\n\n【输出规则】只写 USER 自己下一条输入；可以包含 USER 自己的对白、动作、表情或心理；不得替其他角色创造新的对白、动作或决定；不得写 USER 发完以后对方的反应；不得擅自推进场景；不要前缀、解释、多方案、分析、XML、dream_plot、image###、状态栏、系统信息或标题。最终只输出可以直接放进 SillyTavern 输入框的 USER 消息正文。\n\n<SCENE_BRIEF>\n${brief}\n</SCENE_BRIEF>\n\n<USER_STYLE_SAMPLES>\n${sm}\n</USER_STYLE_SAMPLES>\n\n${dr}\n\n现在只输出 USER 的下一条消息正文。`}

async function profileId(){const M=await manager(),s=settings(),ps=M.getSupportedProfiles();if(!ps.length)throw new Error('没有可用 Connection Profile');if(s.profileId&&ps.some(p=>p.id===s.profileId))return s.profileId;const cur=ctx().extensionSettings?.connectionManager?.selectedProfile;if(cur&&ps.some(p=>p.id===cur))return cur;if(ps.length===1)return ps[0].id;throw new Error('检测到多个 Connection Profile，请点齿轮指定一个')}
function responseText(r){if(typeof r==='string')return r;if(Array.isArray(r))return r.map(x=>typeof x==='string'?x:(x?.text??x?.content??x?.value??'')).join('');const v=r?.content??r?.text??r?.message?.content??r?.message??r?.choices?.[0]?.message?.content??r?.choices?.[0]?.text??r?.output_text??'';return Array.isArray(v)?responseText(v):String(v??'')}
async function ask(prompt,maxTokens,signal){const M=await manager(),s=settings(),id=await profileId(),profile=M.getProfile?.(id);const payload={temperature:s.temperature};if(/^deepseek-v4(?:-|$)/i.test(String(profile?.model??'')))payload.thinking={type:'disabled'};const r=await M.sendRequest(id,prompt,maxTokens,{stream:false,signal,extractData:true,includePreset:false,includeInstruct:false,instructSettings:{}},payload);const t=responseText(r).trim();if(!t){const hasReasoning=Boolean(responseText(r?.reasoning??r?.reasoning_content??r?.choices?.[0]?.message?.reasoning_content??'').trim());throw new Error(hasReasoning?'模型只返回了思考过程，没有返回正文；请增大 Tokens 后重试':'模型没有返回有效文字')}return t}
function put(t){const e=document.querySelector('#send_textarea');if(!e)throw new Error('找不到输入框 #send_textarea');e.value=t;e.dispatchEvent(new Event('input',{bubbles:true}));globalThis.$?.(e).trigger('input');e.focus();try{e.setSelectionRange(t.length,t.length)}catch{}}
function state(x){const b=document.querySelector('#ai_reply_isolator_btn');if(!b)return;if(x==='extracting'){b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i>';b.title='正在抽取剧情事实；再次点击可停止'}else if(x==='writing'){b.innerHTML='<i class="fa-solid fa-pen-nib fa-beat"></i>';b.title='正在帮你写；再次点击可停止'}else{b.innerHTML='<i class="fa-solid fa-wand-magic-sparkles"></i>';b.title='AI 帮我回复'}}
async function generate(){if(busy){abortController?.abort();return}const s=settings(),samples=userSamples(),rc=recent();if(!rc.length)return toast('warning','当前聊天没有可用于帮答的剧情内容。');busy=true;abortController=new AbortController();try{state('extracting');const brief=s.strongIsolation?await ask(extractionPrompt(rc),s.extractorTokens,abortController.signal):rc.map(x=>`${x.role}:\n${x.text}`).join('\n\n');state('writing');let out=sanitize(await ask(replyPrompt(brief,samples,s.includeCurrentDraft?draft():''),s.replyTokens,abortController.signal));if(!out||/<dream_plot|<dream_after_format|image###/i.test(out)){out=sanitize(await ask(replyPrompt(brief,samples,s.includeCurrentDraft?draft():'')+'\n\n上一次输出违规。重新生成，只输出 USER 消息正文。',s.replyTokens,abortController.signal))}if(!out)throw new Error('AI 帮答结果为空');put(out);toast('success',`完成；参考了 ${samples.length} 条你的历史消息。`)}catch(e){if(e?.name==='AbortError')toast('info','已停止 AI 帮答。');else{console.error(`[${ID}]`,e);toast('error',`AI 帮答失败：${e?.message??e}`)}}finally{busy=false;abortController=null;state('idle')}}

function esc(x=''){return String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function openSettings(){const s=settings(),M=await manager(),ps=M.getSupportedProfiles();document.querySelector('#ai_reply_isolator_dialog')?.remove();const d=document.createElement('dialog');d.id='ai_reply_isolator_dialog';d.innerHTML=`<div class="airi-panel"><div class="airi-title"><strong>AI 帮答隔离器</strong><button id="airi_close" class="menu_button">✕</button></div><label class="airi-field"><span>Connection Profile</span><select id="airi_profile"><option value="">自动选择</option>${ps.map(p=>`<option value="${esc(p.id)}">${esc(p.name||p.model||p.id)}</option>`).join('')}</select></label><label class="airi-check"><input id="airi_strong" type="checkbox"><span>强隔离模式<small>先把角色回复转换成中性事实，再生成你的回复。推荐开启。</small></span></label><label class="airi-check"><input id="airi_draft" type="checkbox"><span>参考输入框已有草稿</span></label><div class="airi-grid"><label class="airi-field"><span>用户历史样本</span><input id="airi_samples" type="number" min="3" max="40"></label><label class="airi-field"><span>最近剧情消息</span><input id="airi_context" type="number" min="2" max="20"></label><label class="airi-field"><span>事实抽取 Tokens</span><input id="airi_extract" type="number" min="120" max="1500"></label><label class="airi-field"><span>帮答 Tokens</span><input id="airi_reply" type="number" min="80" max="2000"></label><label class="airi-field"><span>Temperature</span><input id="airi_temp" type="number" min="0" max="2" step="0.05"></label><label class="airi-field"><span>最大输出字符</span><input id="airi_chars" type="number" min="100" max="5000"></label></div><div class="airi-note">只读聊天记录，只把结果写入输入框；不会自动发送，也不直接写入 chat[]。</div><div class="airi-actions"><button id="airi_cancel" class="menu_button">取消</button><button id="airi_save" class="menu_button">保存</button></div></div>`;document.body.appendChild(d);const $=q=>d.querySelector(q);$('#airi_profile').value=s.profileId;$('#airi_strong').checked=s.strongIsolation;$('#airi_draft').checked=s.includeCurrentDraft;$('#airi_samples').value=s.userSamples;$('#airi_context').value=s.contextMessages;$('#airi_extract').value=s.extractorTokens;$('#airi_reply').value=s.replyTokens;$('#airi_temp').value=s.temperature;$('#airi_chars').value=s.maxOutputChars;$('#airi_close').onclick=$('#airi_cancel').onclick=()=>d.close();$('#airi_save').onclick=()=>{s.profileId=$('#airi_profile').value;s.strongIsolation=$('#airi_strong').checked;s.includeCurrentDraft=$('#airi_draft').checked;s.userSamples=+$('#airi_samples').value||12;s.contextMessages=+$('#airi_context').value||6;s.extractorTokens=+$('#airi_extract').value||320;s.replyTokens=+$('#airi_reply').value||420;s.temperature=+$('#airi_temp').value||0.85;s.maxOutputChars=+$('#airi_chars').value||1200;save();d.close();toast('success','设置已保存。')};d.addEventListener('close',()=>d.remove(),{once:true});d.showModal?.()??d.setAttribute('open','')}
function buttons(){if(document.querySelector('#ai_reply_isolator_container'))return true;const send=document.querySelector('#send_but'),ta=document.querySelector('#send_textarea');if(!send||!ta||!send.parentElement)return false;const c=document.createElement('div');c.id='ai_reply_isolator_container';c.innerHTML='<button id="ai_reply_isolator_btn" class="menu_button interactable" type="button" title="AI 帮我回复"><i class="fa-solid fa-wand-magic-sparkles"></i></button><button id="ai_reply_isolator_settings" class="menu_button interactable" type="button" title="AI 帮答设置"><i class="fa-solid fa-gear"></i></button>';send.parentElement.insertBefore(c,send);c.querySelector('#ai_reply_isolator_btn').onclick=generate;c.querySelector('#ai_reply_isolator_settings').onclick=openSettings;return true}
function init(){if(globalThis.__AI_REPLY_ISOLATOR_LOADED__)return;globalThis.__AI_REPLY_ISOLATOR_LOADED__=true;settings();if(buttons())return;const o=new MutationObserver(()=>{if(buttons())o.disconnect()});o.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();

